### ISSUE TITLE
How to use this in angular 2 or angular 4?

### ISSUE THREAD

**Issue by pinku-4132** [TimothyGu/knuth-shuffle-seeded#3]
Hi All,

I am trying to implement this  import this angular 2/ 4,but not able do this.How to use shuffle function with seed value as an argument.

Please please help me on this. I am trying to figure out from past 2 days.Tried so many packages .

**Comment by TimothyGu** [comment]
This package doesn't really have anything to do with Angular, so I'm not sure if I can help you.

**Comment by coolaj86** [comment]
Hahaha. 3 years later. Good form. ;-)
